version: "3.9"

services:
  backend:
    build: ./todo_backend
    container_name: backend
    restart: always
    env_file:
      - ./todo_backend/.env
    ports:
      - "5000:5000"

  frontend:
    build: 
      context: ./todo_frontend
      args:
        API_URL: http://16.170.240.138:5000/api
    container_name: frontend
    restart: always
    ports:
      - "4201:4201"
    depends_on:
      - backend
